# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------
contiki: /home/mike/Repos/usdn
wd:      /home/mike/Repos/usdn/examples/sdn
fmt:     cooja
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results/uSDN
csc:
target:  exp5438

# ----------------------------------------------------------------------------
# Results Options
# packet regex ... https://regex101.com/r/mE5wK0/1
# ----------------------------------------------------------------------------
logtypes:
  cooja:     '^\s*(?P<time>\d+):\s*(?P<node>\d+):'

formatters:
  patterns:
    # uSDN
    - type:   app
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*(?P<state>(TX|RX))\s+(?P<type>\S+)(?:\s+s:(?P<src>\d+)|\s+d:(?P<dest>\d+)|\s+a:(?P<app>\d+)|\s+id:(?P<seq>\d+)|\s+h:(?P<hops>[1-5])|\s+m:(?P<mac>\d+))+.*?$
    - type:   sdn
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*(?P<state>(OUT|BUF|IN))\s+(?P<type>\S+)(?:\s+s:(?P<src>\d+)|\s+d:(?P<dest>\d+)|\s+a:(?P<app>\d+)|\s+id:(?P<seq>\d+)|\s+h:(?P<hops>\d+)|\s+m:(?P<mac>\d+))+.*?$
    - type:   icmp
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*(?:\s+type:(?P<type>\d+)|\s+code:(?P<code>\d+))+.*?$
    # common
    - type:   node
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*h:(?P<hops>\d+), n:(?P<degree>\d+)
    - type:   join
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*(?:\s+n:(?P<id>\d+)|\s+c:(?P<controller>\d+)|\s+dag:(?P<dag>\d+)|\s+dao:(?P<dao>\d+))+.*?$
    - type:   pow
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*](?:\s*PW\s+\(r (?P<all_rdc>\d+\W{1,2}\d+)| \/ (?P<rdc>\d+\W{1,2}\d+))+.*?$
    - type:   all
      regex:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*(?P<state>(TX|RX))\s+(?P<type>\S+)(?:\s+m:(?P<origin>\d+)|\s+t:(?P<target>\d+)|\s+s:(?P<src>\d+)|\s+d:(?P<dest>\d+)|\s+id:(?P<seq>\d+)|\s+h:(?P<hops>[0-5]))+.*?$
  process:
    sdn:
      - filter:
          col:      hops
          min:      1
          max:      5
    node:
      - filter:
          col:      hops
          min:      1
          max:      5

# ----------------------------------------------------------------------------
# Multiflow
# ----------------------------------------------------------------------------
multiflow:
  - id:               1_flow_10s
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        0
      RXNODES:        1
      DELAY:          120
      BRMIN:          10
      BRMAX:          10

  - id:               1_flow
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        0
      RXNODES:        1
      DELAY:          120
      BRMIN:          60
      BRMAX:          75

  - id:               1_flow_p2p
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        [18,19]
      RXNODES:        [20,21]
      DELAY:          [60,60]
      BRMIN:          [60,60]
      BRMAX:          [75,75]

  - id:               2_flow_rr
    NUM_APPS:         2
    flows:
      FLOWIDS:        [1,2]
      TXNODES:        [3,3]
      RXNODES:        [1,1]
      DELAY:          [120,120]
      BRMIN:          [0.23,10]
      BRMAX:          [0.23,10]

# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
# ----------------------------------------------------------------------------
  # - desc:           RPL
  #   type:           usdn
  #   contiki:        /home/mike/Repos/usdn
  #   wd:             /home/mike/Repos/usdn/examples/sdn
  #   csc:            usdn-30-node.csc
  #   log:            RPL-30
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          0
  #     MULTIFLOW:    1
  #   multiflow:      1_flow

  - desc:           uSDN-CSMA-5
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-5-node.csc
    log:            uSDN-CSMA-5
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow


  - desc:           uSDN-CSMA-10
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-10-node.csc
    log:            uSDN-CSMA-10
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CSMA-20
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-20-node.csc
    log:            uSDN-CSMA-20
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CSMA-30
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-30-node.csc
    log:            uSDN-CSMA-30
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CONTIKIMAC-30
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-30-node.csc
    log:            uSDN-CONTIKIMAC-30
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CONTIKIMAC-20
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-20-node.csc
    log:            uSDN-CONTIKIMAC-20
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CONTIKIMAC-10
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-10-node.csc
    log:            uSDN-CONTIKIMAC-10
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

  - desc:           uSDN-CONTIKIMAC-5
    type:           usdn
    contiki:        /home/mike/Repos/usdn
    wd:             /home/mike/Repos/usdn/examples/sdn
    csc:            usdn-5-node.csc
    log:            uSDN-CONTIKIMAC-5
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      FTREFRESH:    0
      FTSRETRY:     0
      FORCENSU:     1
      FTLIFETIME:   300
      NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
      MULTIFLOW:    1
    multiflow:      1_flow

# ----------------------------------------------------------------------------
# compare (comparison) config
# ----------------------------------------------------------------------------
compare:
# ----------------------------------------------------------------------------
  - sims:
    - uSDN
    - RPL
    plots:
      - energy_v_hops
      - pdr_v_hops
      - latency_v_hops
      - join_time
